### ISSUE TITLE
svxbridge.py time.clock() deprecated

### ISSUE THREAD

**Issue by F4HWD** [armel/SpotnikContrib#1]
Hello !

Etant donné que mon système est sous Debian Bullseye, donc incompatible avec les modules Python2.7 comme pyaudio, j'ai testé ta mise à jour de svxbridge.py.

Problème : la fonction time.clock() ligne 9 est dépréciée depuis Python 3.8...et je n'ai que Python 3.9 sur le système. La console me retourne ce message d'erreur dès le lancement : 

`Traceback (most recent call last):
  File "/opt/svxbridge/svxbridge.py", line 9, in <module>
    from time import time, sleep, clock, localtime, strftime
ImportError: cannot import name 'clock' from 'time' (unknown location)`

J'ai essayé de remplacer la fonction par time.perf_counter(), cette fois-ci le programme se lance mais j'obtiens plusieurs lignes `overflow` quand je passe en émission. Cela n'a aucun impact sur le serveur où je souhaite transmettre, rien ne passe.

As-tu une idée ? Merci d'avance.

73 de F4HWD Maxime

**Comment by armel** [comment]
Salut Maxime ;)

La question que je me pose, en regardant ce script (que j'avais uniquement porté sous Python 3), c'est : _à quoi sert cet import ligne 9_ ? :) 
Pour moi, il est tout simplement inutile. Je me contenterais de mettre un # pour le commenter, HI.

Tiens moi au courant.

73 de F4HWN Armel.

**Comment by F4HWD** [comment]
Pour faire suite à ce que nous avons dit sur l'air, le fait de commenter la ligne 9 ne change rien, j'ai toujours le même message d'erreur.

Cependant, j'ai trouvé une solution de contournement : j'ai installé python2 dans les dépôts, puis j'ai téléchargé manuellement le paquet python-pyaudio (pour python2) depuis les dépôts de Debian Buster. Pour PySerial, je l'ai fait pointer sur Python 2 et installé manuellement à l'aide des sources. Concernant SVXBridge, j'ai tout simplement réutilisé la version originale de SP2ONG, disponible aussi dans les dépôts du RRF sur GitHub.

La solution est bien crade, mais ça fonctionne...pour l'instant. Il faudra quand même essayer de résoudre le problème sur le long-terme, un portage fonctionnel sur Python 3 serait le top.

Même si le problème est résolu de façon provisoire, je préfère laisser ce ticket ouvert, au cas où un développeur veuille nous donner un coup de main.

**Comment by F4HWD** [comment]
Petit déterrage de topic ;)

Je suis enfin parvenu à refaire fonctionner le script svxbridge.py en Python 3. La panne venait de l'analyse des trames UDP qui ne commencent plus par 'USRP' comme avec Python 2, mais par b'USRP'. Du coup la détection d'activité ne fonctionnait plus. Un `print(soundData[0:4])` m'a permis d'élucider le problème si jamais tu veux essayer de le reproduire.

En tout cas ça fonctionne bien amintenant, j'ai testé avec le salon perroquet sur le C4FM. Le Pull Request est envoyé avec le patch, libre à toi de l'accepter. En tout cas maintenant, plus d'excuses pour l'intégration des modes numériques sur la prochaine version du Spotnik, HI ! (même s'il y a plus simple...)

A bientôt, 73 de F4HWD Maxime
